name: harbor_pay
description: A Flutter package to accept mobile money payments.
version: 1.0.1
homepage: https://github.com/kmtwum/harbor_pay

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/harbor_pay/assets/mtn.png
    - packages/harbor_pay/assets/vodafone.jpg
    - packages/harbor_pay/assets/airteltigo.jpg