name: harbor_pay
description: A Flutter package to accept mobile / card payments with HarborPay.
version: 0.0.1
author: Kwame Twum<bstoney7@gmail.com>
homepage: https://github.com/kmtwum/harbor_pay

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/harbor_pay/assets/mtn.png
    - packages/harbor_pay/assets/vodafone.jpg
    - packages/harbor_pay/assets/airteltigo.jpg